services:
  music-mongo:
    image: mongo:7-jammy
    restart: unless-stopped
    ports:
      - ${MONGO_PORT}:27017
    volumes:
      - mongo_data:/data/db
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_INITDB_ROOT_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_INITDB_ROOT_PASSWORD}

  crimson-duchess:
    image: crimson-duchess:1.0.0
    container_name: crimson-duches
    restart: unless-stopped
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - ${PORT}:${PORT}
    expose:
      - ${PORT}
    volumes:
      - dowload_music_data:/app/download
      - temp_music_data:/app/temp
    environment:
      DEFAULT_VOICE_CHANNEL_ID: ${DEFAULT_VOICE_CHANNEL_ID}
      DISCORD_APP_ID: ${DISCORD_APP_ID}
      DISCORD_PUBLIC_KEY: ${DISCORD_PUBLIC_KEY}
      DISCORD_TOKEN: ${DISCORD_TOKEN}
      GUILD_ID: ${GUILD_ID}
      PORT: ${PORT}

volumes:
  dowload_music_data:
  temp_music_data:
  mongo_data:
