services:
  crimson-duchess:
    image: ghcr.io/gnocnt2003/crimson-duchess:latest
    container_name: crimson-duches
    restart: unless-stopped
    ports:
      - ${PORT}:${PORT}
    expose:
      - ${PORT}
    volumes:
      - dowload_music_data:/app/download
      - temp_music_data:/app/temp
    environment:
      DEFAULT_VOICE_CHANNEL_ID: ${DEFAULT_VOICE_CHANNEL_ID}
      DISCORD_APP_ID: ${DISCORD_APP_ID}
      DISCORD_PUBLIC_KEY: ${DISCORD_PUBLIC_KEY}
      DISCORD_TOKEN: ${DISCORD_TOKEN}
      GUILD_ID: ${GUILD_ID}
      PORT: ${PORT}

volumes:
  dowload_music_data:
  temp_music_data: